### ISSUE TITLE
CSSObj seems slow

### ISSUE THREAD

**Issue by PhiLhoSoft** [cssobj/cssobj#12] opened 2016-12-19 09:34 UTC
I contribute to the https://github.com/hellofresh/css-in-js-perf-tests/ project, which aims to test the performance, and to examine the API and the results, of several CSS-in-JS projects, focusing on those view-agnostic and working on server side, among other things.
I added CSSObj to the project, and it seems it is a bit slow: https://github.com/hellofresh/css-in-js-perf-tests/issues/23
It is probably because [I didn't made optimal usage of the API](https://github.com/hellofresh/css-in-js-perf-tests/blob/master/src/simple-test/cases/cssobj.js), or perhaps the library is not performing well in the context of the tests (the benchmark code calls the test case lot of times to do its stats).
For example, the https://engineering.hellofresh.com/the-css-in-js-battle-89c34a7a83ea article explains that JSS perf wasn't good because the global CSS in the library instance was growing, so they added a reset / flush call in each test case.
Perhaps your library has a similar problem, but I haven't found such function to clean up the CSS after rendering.
Do you have any tip to improve the performance?

**Comment by futurist** [comment] 2016-12-19 10:44
I also noticed that, and I ran the perf test you mentioned several days ago.

It's due to several things:

1. The selector parser can be improved (should keep safety and stable), it's WIP now

2. The test env is in server side, but CSS-in-JS mainly in browser env, more of the factor should be considered, like `<style>` tag ceation, CSS Rules creation and updating.

3. For server side rendering, and one time generation, cssobj is not fast since it have to build a virtual node tree inside. But after that, the `result.update` is very fast, since the virtual node tree is built up.

4. The performance did have some improvement space internally, that already in my schedule.

5. The direction of cssobj now is: `CSSOM` virtualization, and `Nested selector` optimization

**Comment by futurist** [comment] 2016-12-19 12:49
The first step that can do: [cssobj-core](https://github.com/cssobj/cssobj-core) contains some functional usage of array method, like `forEach`, `reduce` etc., that slow down the virtual node tree building. (Since function is heavy than `for/while` when loop)

Some one want try to transform? if you can pass all the testing.

**Comment by futurist** [comment] 2016-12-20 11:19
I've optimized the selector parser, smaller size, and better perf, see [1.0.4](https://github.com/cssobj/cssobj/releases/tag/1.0.4)

Also, I download the [pref-test](https://github.com/hellofresh/css-in-js-perf-tests/), and refactored all `Array.forEach` `Array.reduce` etc. into `for loop`, the perf increased, but not more. So I reverted it, since the functional style is more maintainable.

And I've been going through all code base, try to catch if there's some thing doing wrong, but not found so far.

So the problem is the whole difference of feature set, and different CSS-in-JS direction, other libs don't have **Virtual Stylesheet Node**, no need building it. In this aspect, the pref test is not fair, please kindly remove cssobj from it if you can.

If you have another **Virtual Stylesheet** lib, we can compare the pref, that make sense.

I'm going to close this issue, since cssobj is not the same internally. Just use it in your project, and you can really feel everything.

**Closed by futurist** 2016-12-20 11:19 UTC

**Comment by PhiLhoSoft** [comment] 2016-12-20 16:46
Thanks for all the testing and notes.

For me, the speed isn't a real issue, I opened the issue in case I missed something that would boost the performance, like cache flushing, etc..
I will keep your library in the test, but will add a note in the readme to indicate that speed is better in the client. But the test goes beyond speed, anyway: we also look at size of generated CSS, at generated code too, etc. There are several criteria to choose a library.

I plan to make a project to test all these libraries in a small client project, perhaps CSSObj will shine there... 😄

**Comment by futurist** [comment] 2016-12-28 00:07
`cssobj` is the lib for **stylesheet CRUD**, this is very different according to all other CSS-in-JS libs.

In fact, the position of `cssobj` is **stylesheet manager at runtime**, so the compare with other CSS-in-JS libs make little sense.

The **virtual CSS node** code base is well organized, and the speed is already optimized, there's little thing can do about the pref, and till now nobody report the problem about the perf.
